# Generated by Django 5.2.4 on 2026-02-28 11:19

import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


from django.utils.text import slugify


def copy_service_type_to_service_types(apps, schema_editor):
    Provider = apps.get_model("Myapp", "Provider")
    for provider in Provider.objects.all().only("id", "service_type_id"):
        if provider.service_type_id:
            provider.service_types.add(provider.service_type_id)


SERVICE_TYPE_NAMES = ['Badana / boya ustası',
 'Alçı ustası',
 'Sıva ustası',
 'Fayans / seramik ustası',
 'Parke ustası (laminat, masif parke)',
 'Mermer ustası',
 'Mantolama ustası',
 'Çatı ustası',
 'İzolasyon ustası (su / ısı / ses yalıtımı)',
 'Kalıpçı',
 'Demirci (inşaat demiri)',
 'Duvar kırma & tadilat ustası',
 'Su tesisatçısı (tesisatçı)',
 'Doğalgaz ustası',
 'Kombi servisi',
 'Petek temizleme ustası',
 'Klima montaj & bakım ustası',
 'Elektrikçi',
 'Jeneratör teknik servisi',
 'Güneş enerjisi sistemi ustası',
 'Havalandırma ustası',
 'Çilingir',
 'Oto çilingir',
 'Alarm sistemi kurulumcusu',
 'Kamera (CCTV) montaj ustası',
 'Akıllı kilit / smart home kurulum',
 'Marangoz',
 'Mobilya montaj ustası',
 'Mutfak dolabı ustası',
 'Vestiyer / dolap yapımı',
 'Kapı ustası',
 'PVC doğrama ustası',
 'Cam balkon ustası',
 'Camcı',
 'Beyaz eşya tamircisi',
 'Buzdolabı servisi',
 'Çamaşır makinesi servisi',
 'Bulaşık makinesi servisi',
 'Televizyon tamircisi',
 'Küçük ev aletleri tamiri',
 'Bilgisayar teknik servisi',
 'Telefon tamircisi',
 'Koltuk yıkama',
 'Halı yıkama',
 'Ev temizliği ustası',
 'İnşaat sonrası temizlik',
 'İlaçlama (haşere kontrol)',
 'Baca temizleme',
 'Su deposu temizliği',
 'Bahçıvan',
 'Peyzaj ustası',
 'Çim ekimi & bakım',
 'Otomatik sulama sistemi kurulumu',
 'Havuz bakım ustası',
 'Oto elektrikçi',
 'Oto mekanik ustası',
 'Lastikçi',
 'Kaporta ustası',
 'Oto boya ustası',
 'Stor perde / zebra perde montajı',
 'Avize montajı',
 'Duvara TV montajı',
 'Duvar delme / montaj işleri',
 'Nakliyeci',
 'Asansör bakım servisi']


def unique_slug(name, taken):
    base = slugify(name) or "hizmet"
    candidate = base
    suffix = 2
    while candidate in taken:
        candidate = f"{base}-{suffix}"
        suffix += 1
    taken.add(candidate)
    return candidate


def replace_service_types(apps, schema_editor):
    ServiceType = apps.get_model("Myapp", "ServiceType")
    ServiceRequest = apps.get_model("Myapp", "ServiceRequest")

    desired_names = set(SERVICE_TYPE_NAMES)
    slug_pool = set(ServiceType.objects.values_list("slug", flat=True))

    by_name = {item.name: item for item in ServiceType.objects.all()}
    desired_objects = []
    for name in SERVICE_TYPE_NAMES:
        item = by_name.get(name)
        if item is None:
            item = ServiceType.objects.create(
                name=name,
                slug=unique_slug(name, slug_pool),
            )
        desired_objects.append(item)

    fallback = desired_objects[0]
    old_items = ServiceType.objects.exclude(name__in=desired_names)
    old_ids = list(old_items.values_list("id", flat=True))

    if old_ids:
        ServiceRequest.objects.filter(service_type_id__in=old_ids).update(service_type_id=fallback.id)
        old_items.delete()


class Migration(migrations.Migration):

    replaces = [('Myapp', '0001_initial'), ('Myapp', '0002_provider_coordinates'), ('Myapp', '0003_servicerequest_customer_customerprofile'), ('Myapp', '0004_providerrating'), ('Myapp', '0005_alter_providerrating_unique_together_and_more'), ('Myapp', '0006_alter_servicerequest_status_provideroffer'), ('Myapp', '0007_remove_provider_service_type_provider_service_types'), ('Myapp', '0008_provider_user'), ('Myapp', '0009_alter_servicerequest_status'), ('Myapp', '0010_replace_service_types_with_full_catalog'), ('Myapp', '0011_serviceappointment'), ('Myapp', '0012_provideroffer_quote_amount_provideroffer_quote_note_and_more'), ('Myapp', '0013_customerprofile_phone_verified_and_more'), ('Myapp', '0014_remove_customerprofile_phone_verified_and_more'), ('Myapp', '0015_alter_serviceappointment_status'), ('Myapp', '0016_alter_provideroffer_status_and_more'), ('Myapp', '0017_servicerequest_matched_at_and_more'), ('Myapp', '0018_alter_credittransaction_transaction_type'), ('Myapp', '0019_schedulerheartbeat_idempotencyrecord_workflowevent'), ('Myapp', '0020_schedulerlock'), ('Myapp', '0021_customerprofile_phone_verified_at_and_more'), ('Myapp', '0022_remove_phoneverificationcode_user_and_more'), ('Myapp', '0023_alter_provideroffer_status_and_more'), ('Myapp', '0024_remove_provideroffer_quote_amount_and_more'), ('Myapp', '0025_notificationcursor'), ('Myapp', '0026_alter_notificationcursor_workflow_seen_at'), ('Myapp', '0027_alter_provideravailabilityslot_weekday')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('district', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='Myapp.servicetype')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_types', models.ManyToManyField(blank=True, related_name='providers', to='Myapp.servicetype')),
            ],
            options={
                'ordering': ['-is_available', '-rating', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=80)),
                ('district', models.CharField(max_length=80)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('pending_provider', 'Usta Onayi Bekleniyor'), ('matched', 'Eslestirildi'), ('completed', 'Tamamlandi')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='Myapp.provider')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='Myapp.servicetype')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_ratings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Myapp.provider')),
                ('service_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_rating', to='Myapp.servicerequest')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='ProviderOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=24, unique=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul'), ('rejected', 'Red'), ('expired', 'Sure Doldu'), ('failed', 'Gonderim Basarisiz')], default='pending', max_length=20)),
                ('last_delivery_detail', models.CharField(blank=True, max_length=120)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='Myapp.provider')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_offers', to='Myapp.servicerequest')),
            ],
            options={
                'ordering': ['service_request_id', 'sequence'],
                'unique_together': {('service_request', 'provider')},
            },
        ),
        migrations.RunPython(
            code=copy_service_type_to_service_types,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='provider',
            name='service_type',
        ),
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'Yeni'), ('pending_provider', 'Usta Onayi Bekleniyor'), ('matched', 'Eslestirildi'), ('completed', 'Tamamlandi'), ('cancelled', 'Iptal Edildi')], default='new', max_length=20),
        ),
        migrations.RunPython(
            code=replace_service_types,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('customer_note', models.TextField(blank=True)),
                ('provider_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Usta Onayı Bekleniyor'), ('pending_customer', 'Müşteri Onayı Bekleniyor'), ('confirmed', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'Müşteri İptal Etti'), ('completed', 'Tamamlandı')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Myapp.provider')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='Myapp.servicerequest')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.AddField(
            model_name='provideroffer',
            name='quote_note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'Yeni'), ('pending_provider', 'Usta Onayı Bekleniyor'), ('pending_customer', 'Müşteri Seçimi Bekleniyor'), ('matched', 'Eşleştirildi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='provideroffer',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provideroffer',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provideroffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul'), ('rejected', 'Red'), ('expired', 'Süre Doldu'), ('failed', 'Gönderim Başarısız')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('customer', 'Müşteri'), ('provider', 'Usta')], max_length=20)),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_messages', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Myapp.servicerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='matched_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_requests', to='Myapp.provideroffer'),
        ),
        migrations.CreateModel(
            name='SchedulerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=80, unique=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['worker_name'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('scope', models.CharField(max_length=80)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('request', 'Talep'), ('appointment', 'Randevu')], max_length=20)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('actor_role', models.CharField(choices=[('customer', 'Müşteri'), ('provider', 'Usta'), ('system', 'Sistem')], default='system', max_length=20)),
                ('source', models.CharField(choices=[('user', 'Kullanıcı'), ('scheduler', 'Zamanlayıcı'), ('system', 'Sistem')], default='system', max_length=20)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_events', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_events', to='Myapp.serviceappointment')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_events', to='Myapp.servicerequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SchedulerLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=80, unique=True)),
                ('lock_owner', models.CharField(blank=True, max_length=64)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_acquired_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['worker_name'],
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotificationCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_cursor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderAvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='Myapp.provider')),
            ],
            options={
                'ordering': ['provider_id', 'weekday', 'start_time'],
                'unique_together': {('provider', 'weekday', 'start_time', 'end_time')},
            },
        ),
    ]
