# Generated by Django 5.2.4 on 2026-02-22 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_providerrating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='providerrating',
            name='service_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_rating', to='Myapp.servicerequest'),
        ),
    ]
