# Generated by Django 5.2.4 on 2026-02-22 14:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_alter_providerrating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'Yeni'), ('pending_provider', 'Usta Onayi Bekleniyor'), ('matched', 'Eslestirildi'), ('completed', 'Tamamlandi')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='ProviderOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=24, unique=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul'), ('rejected', 'Red'), ('expired', 'Sure Doldu'), ('failed', 'Gonderim Basarisiz')], default='pending', max_length=20)),
                ('last_delivery_detail', models.CharField(blank=True, max_length=120)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='Myapp.provider')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_offers', to='Myapp.servicerequest')),
            ],
            options={
                'ordering': ['service_request_id', 'sequence'],
                'unique_together': {('service_request', 'provider')},
            },
        ),
    ]
