# Generated by Django 5.2.4 on 2026-02-22 20:35

from django.db import migrations, models


def copy_service_type_to_service_types(apps, schema_editor):
    Provider = apps.get_model("Myapp", "Provider")
    for provider in Provider.objects.all().only("id", "service_type_id"):
        if provider.service_type_id:
            provider.service_types.add(provider.service_type_id)


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_alter_servicerequest_status_provideroffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='service_types',
            field=models.ManyToManyField(blank=True, related_name='providers', to='Myapp.servicetype'),
        ),
        migrations.RunPython(copy_service_type_to_service_types, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='provider',
            name='service_type',
        ),
    ]
