# Generated by Django 5.2.4 on 2026-02-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_provider_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'Yeni'), ('pending_provider', 'Usta Onayi Bekleniyor'), ('matched', 'Eslestirildi'), ('completed', 'Tamamlandi'), ('cancelled', 'Iptal Edildi')], default='new', max_length=20),
        ),
    ]
