# Generated by Codex on 2026-02-23

from django.db import migrations
from django.utils.text import slugify


SERVICE_TYPE_NAMES = [
    "Badana / boya ustası",
    "Alçı ustası",
    "Sıva ustası",
    "Fayans / seramik ustası",
    "Parke ustası (laminat, masif parke)",
    "Mermer ustası",
    "Mantolama ustası",
    "Çatı ustası",
    "İzolasyon ustası (su / ısı / ses yalıtımı)",
    "Kalıpçı",
    "Demirci (inşaat demiri)",
    "Duvar kırma & tadilat ustası",
    "Su tesisatçısı (tesisatçı)",
    "Doğalgaz ustası",
    "Kombi servisi",
    "Petek temizleme ustası",
    "Klima montaj & bakım ustası",
    "Elektrikçi",
    "Jeneratör teknik servisi",
    "Güneş enerjisi sistemi ustası",
    "Havalandırma ustası",
    "Çilingir",
    "Oto çilingir",
    "Alarm sistemi kurulumcusu",
    "Kamera (CCTV) montaj ustası",
    "Akıllı kilit / smart home kurulum",
    "Marangoz",
    "Mobilya montaj ustası",
    "Mutfak dolabı ustası",
    "Vestiyer / dolap yapımı",
    "Kapı ustası",
    "PVC doğrama ustası",
    "Cam balkon ustası",
    "Camcı",
    "Beyaz eşya tamircisi",
    "Buzdolabı servisi",
    "Çamaşır makinesi servisi",
    "Bulaşık makinesi servisi",
    "Televizyon tamircisi",
    "Küçük ev aletleri tamiri",
    "Bilgisayar teknik servisi",
    "Telefon tamircisi",
    "Koltuk yıkama",
    "Halı yıkama",
    "Ev temizliği ustası",
    "İnşaat sonrası temizlik",
    "İlaçlama (haşere kontrol)",
    "Baca temizleme",
    "Su deposu temizliği",
    "Bahçıvan",
    "Peyzaj ustası",
    "Çim ekimi & bakım",
    "Otomatik sulama sistemi kurulumu",
    "Havuz bakım ustası",
    "Oto elektrikçi",
    "Oto mekanik ustası",
    "Lastikçi",
    "Kaporta ustası",
    "Oto boya ustası",
    "Stor perde / zebra perde montajı",
    "Avize montajı",
    "Duvara TV montajı",
    "Duvar delme / montaj işleri",
    "Nakliyeci",
    "Asansör bakım servisi",
]


def unique_slug(name, taken):
    base = slugify(name) or "hizmet"
    candidate = base
    suffix = 2
    while candidate in taken:
        candidate = f"{base}-{suffix}"
        suffix += 1
    taken.add(candidate)
    return candidate


def replace_service_types(apps, schema_editor):
    ServiceType = apps.get_model("Myapp", "ServiceType")
    ServiceRequest = apps.get_model("Myapp", "ServiceRequest")

    desired_names = set(SERVICE_TYPE_NAMES)
    slug_pool = set(ServiceType.objects.values_list("slug", flat=True))

    by_name = {item.name: item for item in ServiceType.objects.all()}
    desired_objects = []
    for name in SERVICE_TYPE_NAMES:
        item = by_name.get(name)
        if item is None:
            item = ServiceType.objects.create(
                name=name,
                slug=unique_slug(name, slug_pool),
            )
        desired_objects.append(item)

    fallback = desired_objects[0]
    old_items = ServiceType.objects.exclude(name__in=desired_names)
    old_ids = list(old_items.values_list("id", flat=True))

    if old_ids:
        ServiceRequest.objects.filter(service_type_id__in=old_ids).update(service_type_id=fallback.id)
        old_items.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0009_alter_servicerequest_status"),
    ]

    operations = [
        migrations.RunPython(replace_service_types, migrations.RunPython.noop),
    ]
