# Generated by Django 5.2.4 on 2026-02-23 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_replace_service_types_with_full_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('customer_note', models.TextField(blank=True)),
                ('provider_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Usta Onayi Bekleniyor'), ('confirmed', 'Onaylandi'), ('rejected', 'Reddedildi'), ('cancelled', 'Musteri Iptal Etti'), ('completed', 'Tamamlandi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Myapp.provider')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='Myapp.servicerequest')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
    ]
