# Generated by Django 5.2.4 on 2026-02-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_serviceappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideroffer',
            name='quote_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='provideroffer',
            name='quote_note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'Yeni'), ('pending_provider', 'Usta Onayi Bekleniyor'), ('pending_customer', 'Musteri Secimi Bekleniyor'), ('matched', 'Eslestirildi'), ('completed', 'Tamamlandi'), ('cancelled', 'Iptal Edildi')], default='new', max_length=20),
        ),
    ]
