# Generated by Django 5.2.4 on 2026-02-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0013_customerprofile_phone_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone_verified',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='phone_verified',
        ),
        migrations.DeleteModel(
            name='PhoneVerification',
        ),
    ]
