# Generated by Django 5.2.4 on 2026-02-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0014_remove_customerprofile_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Usta Onayi Bekleniyor'), ('pending_customer', 'Musteri Onayi Bekleniyor'), ('confirmed', 'Onaylandi'), ('rejected', 'Reddedildi'), ('cancelled', 'Musteri Iptal Etti'), ('completed', 'Tamamlandi')], default='pending', max_length=20),
        ),
    ]
