# Generated by Django 5.2.4 on 2026-02-23 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0015_alter_serviceappointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideroffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul'), ('rejected', 'Red'), ('expired', 'Süre Doldu'), ('failed', 'Gönderim Başarısız')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Usta Onayı Bekleniyor'), ('pending_customer', 'Müşteri Onayı Bekleniyor'), ('confirmed', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'Müşteri İptal Etti'), ('completed', 'Tamamlandı')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicemessage',
            name='sender_role',
            field=models.CharField(choices=[('customer', 'Müşteri'), ('provider', 'Usta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'Yeni'), ('pending_provider', 'Usta Onayı Bekleniyor'), ('pending_customer', 'Müşteri Seçimi Bekleniyor'), ('matched', 'Eşleştirildi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='ProviderWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='Myapp.provider')),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('welcome', 'Hos Geldin Kredisi'), ('admin_load', 'Admin Yukleme'), ('package_purchase', 'Paket Satin Alimi'), ('quote_fee', 'Teklif Kredisi'), ('adjustment', 'Duzeltme')], max_length=30)),
                ('amount', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='Myapp.provider')),
                ('reference_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='Myapp.provideroffer')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Myapp.providerwallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
