# Generated by Django 5.2.4 on 2026-02-23 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0016_alter_provideroffer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='matched_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_requests', to='Myapp.provideroffer'),
        ),
    ]
