# Generated by Django 5.2.4 on 2026-02-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0017_servicerequest_matched_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('welcome', 'Hoş Geldin Kredisi'), ('admin_load', 'Admin Yükleme'), ('package_purchase', 'Paket Satın Alımı'), ('quote_fee', 'Teklif Kredisi'), ('adjustment', 'Düzeltme')], max_length=30),
        ),
    ]
