# Generated by Django 5.2.4 on 2026-02-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0019_schedulerheartbeat_idempotencyrecord_workflowevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=80, unique=True)),
                ('lock_owner', models.CharField(blank=True, max_length=64)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_acquired_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['worker_name'],
            },
        ),
    ]
