# Generated by Django 5.2.4 on 2026-02-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0022_remove_phoneverificationcode_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideroffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul'), ('rejected', 'Red'), ('expired', 'Süre Doldu'), ('failed', 'Gönderim Başarısız')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Usta Onayı Bekleniyor'), ('pending_customer', 'Müşteri Onayı Bekleniyor'), ('confirmed', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'Müşteri İptal Etti'), ('completed', 'Tamamlandı')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicemessage',
            name='sender_role',
            field=models.CharField(choices=[('customer', 'Müşteri'), ('provider', 'Usta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'Yeni'), ('pending_provider', 'Usta Onayı Bekleniyor'), ('pending_customer', 'Müşteri Seçimi Bekleniyor'), ('matched', 'Eşleştirildi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='actor_role',
            field=models.CharField(choices=[('customer', 'Müşteri'), ('provider', 'Usta'), ('system', 'Sistem')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='source',
            field=models.CharField(choices=[('user', 'Kullanıcı'), ('scheduler', 'Zamanlayıcı'), ('system', 'Sistem')], default='system', max_length=20),
        ),
    ]
