# Generated by Django 5.2.4 on 2026-02-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0023_alter_provideroffer_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideroffer',
            name='quote_amount',
        ),
        migrations.DeleteModel(
            name='EscrowPayment',
        ),
    ]
