# Generated by Django 5.2.4 on 2026-02-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0025_notificationcursor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcursor',
            name='workflow_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
