# Generated by Django 5.2.4 on 2026-02-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0026_alter_notificationcursor_workflow_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideravailabilityslot',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')]),
        ),
    ]
