# Generated by Django 5.2.4 on 2026-02-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial_squashed_0027_alter_provideravailabilityslot_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='created_ip',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
