# Generated by Django 5.2.4 on 2026-02-28 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0028_servicerequest_created_ip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('request_status', 'Talep Durum Degisimi'), ('appointment_status', 'Randevu Durum Degisimi'), ('message_sent', 'Mesaj Gonderildi')], max_length=32)),
                ('actor_role', models.CharField(choices=[('customer', 'Musteri'), ('provider', 'Usta'), ('system', 'Sistem')], default='system', max_length=20)),
                ('source', models.CharField(choices=[('user', 'Kullanici'), ('scheduler', 'Zamanlayici'), ('system', 'Sistem')], default='system', max_length=20)),
                ('summary', models.CharField(max_length=240)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='Myapp.serviceappointment')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='Myapp.servicemessage')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='Myapp.servicerequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='Myapp_activ_action__7534f6_idx'), models.Index(fields=['service_request', 'created_at'], name='Myapp_activ_service_fb6e91_idx'), models.Index(fields=['appointment', 'created_at'], name='Myapp_activ_appoint_a67472_idx'), models.Index(fields=['actor_user', 'created_at'], name='Myapp_activ_actor_u_cf2f3b_idx')],
            },
        ),
    ]
