# Generated by Django 5.2.4 on 2026-02-28 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0029_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(default=500)),
                ('message', models.CharField(max_length=500)),
                ('traceback', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status_code', 'created_at'], name='Myapp_error_status__aec0ea_idx'), models.Index(fields=['resolved_at', 'created_at'], name='Myapp_error_resolve_b40dd9_idx'), models.Index(fields=['user', 'created_at'], name='Myapp_error_user_id_30e413_idx')],
            },
        ),
    ]
