# Generated by Django 5.2.4 on 2026-03-01 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0030_errorlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=16)),
                ('device_id', models.CharField(max_length=120)),
                ('push_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('locale', models.CharField(blank=True, max_length=32)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['user', 'last_seen_at'], name='Myapp_mobil_user_id_062bd6_idx'), models.Index(fields=['platform', 'last_seen_at'], name='Myapp_mobil_platfor_328229_idx')],
                'unique_together': {('user', 'platform', 'device_id')},
            },
        ),
    ]
