from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .mobile_api_views import (
    MobileCreateRequestView,
    MobileCustomerCancelAppointmentView,
    MobileCustomerCancelRequestView,
    MobileCustomerCompleteRequestView,
    MobileCustomerCreateAppointmentView,
    MobileCustomerRateRequestView,
    MobileCustomerRequestsView,
    MobileCustomerSelectOfferView,
    MobileDeviceRegisterView,
    MobileLoginView,
    MobileMarketplaceBootstrapView,
    MobileMeView,
    MobileNotificationPreferencesView,
    MobileNotificationReadView,
    MobileNotificationsReadAllView,
    MobileNotificationsView,
    MobileProviderAcceptOfferView,
    MobileProviderCompleteAppointmentView,
    MobileProviderConfirmAppointmentView,
    MobileProviderDetailView,
    MobileProviderDashboardView,
    MobileProviderRejectAppointmentView,
    MobileProviderRejectOfferView,
    MobileProviderReleaseRequestView,
    MobileProviderWithdrawOfferView,
    MobileProvidersView,
    MobileRequestDetailView,
    MobileRequestMessagesView,
)


urlpatterns = [
    path("auth/login/", MobileLoginView.as_view(), name="mobile_login"),
    path("auth/refresh/", TokenRefreshView.as_view(), name="mobile_token_refresh"),
    path("me/", MobileMeView.as_view(), name="mobile_me"),
    path("marketplace/bootstrap/", MobileMarketplaceBootstrapView.as_view(), name="mobile_marketplace_bootstrap"),
    path("marketplace/providers/", MobileProvidersView.as_view(), name="mobile_providers"),
    path("marketplace/providers/<int:provider_id>/", MobileProviderDetailView.as_view(), name="mobile_provider_detail"),
    path("customer/requests/create/", MobileCreateRequestView.as_view(), name="mobile_create_request"),
    path("customer/requests/", MobileCustomerRequestsView.as_view(), name="mobile_customer_requests"),
    path("customer/requests/<int:request_id>/cancel/", MobileCustomerCancelRequestView.as_view(), name="mobile_customer_cancel_request"),
    path("customer/requests/<int:request_id>/complete/", MobileCustomerCompleteRequestView.as_view(), name="mobile_customer_complete_request"),
    path("customer/requests/<int:request_id>/rating/", MobileCustomerRateRequestView.as_view(), name="mobile_customer_rate_request"),
    path("customer/requests/<int:request_id>/appointments/", MobileCustomerCreateAppointmentView.as_view(), name="mobile_customer_create_appointment"),
    path("customer/requests/<int:request_id>/appointments/cancel/", MobileCustomerCancelAppointmentView.as_view(), name="mobile_customer_cancel_appointment"),
    path("customer/requests/<int:request_id>/offers/<int:offer_id>/select/", MobileCustomerSelectOfferView.as_view(), name="mobile_customer_select_offer"),
    path("provider/dashboard/", MobileProviderDashboardView.as_view(), name="mobile_provider_dashboard"),
    path("provider/offers/<int:offer_id>/accept/", MobileProviderAcceptOfferView.as_view(), name="mobile_provider_accept_offer"),
    path("provider/offers/<int:offer_id>/reject/", MobileProviderRejectOfferView.as_view(), name="mobile_provider_reject_offer"),
    path("provider/offers/<int:offer_id>/withdraw/", MobileProviderWithdrawOfferView.as_view(), name="mobile_provider_withdraw_offer"),
    path("provider/appointments/<int:appointment_id>/confirm/", MobileProviderConfirmAppointmentView.as_view(), name="mobile_provider_confirm_appointment"),
    path("provider/appointments/<int:appointment_id>/reject/", MobileProviderRejectAppointmentView.as_view(), name="mobile_provider_reject_appointment"),
    path("provider/appointments/<int:appointment_id>/complete/", MobileProviderCompleteAppointmentView.as_view(), name="mobile_provider_complete_appointment"),
    path("provider/requests/<int:request_id>/release/", MobileProviderReleaseRequestView.as_view(), name="mobile_provider_release_request"),
    path("requests/<int:request_id>/detail/", MobileRequestDetailView.as_view(), name="mobile_request_detail"),
    path("requests/<int:request_id>/messages/", MobileRequestMessagesView.as_view(), name="mobile_request_messages"),
    path("notifications/", MobileNotificationsView.as_view(), name="mobile_notifications"),
    path("notifications/read-all/", MobileNotificationsReadAllView.as_view(), name="mobile_notifications_read_all"),
    path("notifications/<str:entry_id>/read/", MobileNotificationReadView.as_view(), name="mobile_notification_read"),
    path(
        "notification-preferences/",
        MobileNotificationPreferencesView.as_view(),
        name="mobile_notification_preferences",
    ),
    path("devices/register/", MobileDeviceRegisterView.as_view(), name="mobile_device_register"),
]
